### ISSUE TITLE
Hello, I, Alarical, has a very many big issue with this repository.

### ISSUE THREAD

**Issue by CatLover39** [noemtdev/auth-bot#1]
1: This rerposoitory uses py cord, i am not a big fan of py cord.
2: This repositry totally uses oauth wwhich is rat btw
3: This rerpsostirorhy has outdate import or someting liek that dependenscies mhmhmhmhm
4: nom might maybe be a nazi ( we hate nazis )
5: i heard its ok to punch nazis
6: noemtdev is 
7: dude idk
8: rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz
9: hi nom
10: stop doing python

**Comment by CatLover39** [comment]
OH, AND I ALSO HAVE AN ISSUE WITH YOUR PRONOUNS.

**Comment by noemtdev** [comment]
1. Go look for another repository then, py-cord is very similar to discord.py in many ways!
2. The oauth2 section is not related to microsoft oauth ratting, it's discord authentication to allow the bot owner to restore you to their server
3. I dont think it has outdated imports
4. uhm
5. yes it is
6. hi
7. same
8. second longest german word
9. hi
10. unfortunatly, I will not

**Comment by CatLover39** [comment]
Hello "noemtdev" as a response to your "sillyness" i will hereby be replying,
